name: image_extensions
description: A simple command-line application.
version: 0.0.0
homepage: https://github.com/vanxh/image_extensions
repository: https://github.com/vanxh/image_extensions

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  image: ^3.1.1
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
